r"""The Gröbner walk: conversion of Gröbner bases between monomial orders.

SymPy converts Gröbner bases with the FGLM algorithm
(:meth:`sympy.polys.polytools.GroebnerBasis.fglm`), which only applies to
zero-dimensional ideals. The Gröbner walk of Collart, Kalkbrener and Mall
[1]_ works for every ideal: the source and target orders are represented by
weight vectors $\omega$ and $\tau$, and the basis is transformed along the
segment from $\omega$ to $\tau$. At every point where the ordering of the
monomials of the basis changes, the *initial forms* of the basis elements
(their terms of maximal weight) are computed, a Gröbner basis of the ideal
they generate is computed with the Buchberger algorithm keeping track of
the representations, and the representations are used to lift it to a
Gröbner basis of the whole ideal for the new weight. The initial forms are
usually much smaller than the polynomials, so each step is cheap.

The lifting used here is the one of [2]_: if $G$ is the basis for the
previous order and $\omega$ lies in the closure of its Gröbner cone, then
for every element $h$ of a Gröbner basis of the initial ideal the
polynomial $h - \mathrm{NF}_G(h)$ (normal form for the previous order)
belongs to the ideal and has initial form $h$. This allows the initial
forms to be handled by SymPy's own Buchberger implementation;
:func:`extended_groebner`, a Buchberger algorithm keeping the
representations, is kept as an alternative lifting (``lift='cofactors'``).

For zero-dimensional ideals the FGLM algorithm of SymPy is usually faster
than the walk; :meth:`sympy_extras.polys.ideals.Ideal.change_order` uses
it in that case.

The weight orders used along the walk are :class:`~.WeightOrder` instances:
a weight vector refined by the target order.

References
==========

.. [1] S. Collart, M. Kalkbrener, D. Mall, Converting bases with the
       Gröbner walk, J. Symbolic Computation 24 (1997) 465-469.
.. [2] B. Amrhein, O. Gloor, W. Küchlin, On the walk, Theoretical Computer
       Science 187 (1997) 179-202.
"""
from __future__ import annotations

from fractions import Fraction
from math import lcm

from sympy.polys.groebnertools import groebner as _groebner, red_groebner, is_groebner
from sympy.polys.monomials import monomial_lcm, monomial_div
from sympy.polys.orderings import lex, grlex, grevlex, ilex, igrlex, igrevlex

from .orderings import WeightOrder, as_order

__all__ = ['groebner_walk', 'initial_form', 'extended_groebner']


def _weight_of(order, nvars, G):
    """A weight vector in the closure of the Gröbner cone of ``G`` for the
    given order: the degree vector for graded orders, a vector of
    decreasing powers for ``lex``."""
    order = as_order(order)
    if isinstance(order, WeightOrder):
        return tuple(Fraction(w) for w in order.weights)
    if order in (grlex, grevlex):
        return tuple(Fraction(1) for _ in range(nvars))
    if order == lex:
        d = 1 + max([max(sum(m) for m in g.monoms()) for g in G] + [1])
        return tuple(Fraction(d)**(nvars - 1 - i) for i in range(nvars))
    if order in (ilex, igrlex, igrevlex):
        raise ValueError("inverse orders are not global orders")
    raise ValueError("no weight vector is known for the order %s" % (order,))


def _target_weight(order, nvars):
    """The weight vector such that its refinement by ``order`` is ``order``
    itself."""
    order = as_order(order)
    if isinstance(order, WeightOrder):
        return tuple(Fraction(w) for w in order.weights)
    if order in (grlex, grevlex):
        return tuple(Fraction(1) for _ in range(nvars))
    if order == lex:
        return tuple(Fraction(1 if i == 0 else 0) for i in range(nvars))
    raise ValueError("no weight vector is known for the order %s" % (order,))


def _integral(weights):
    """Scale a rational weight vector to integers."""
    den = 1
    for w in weights:
        den = lcm(den, Fraction(w).denominator)
    return tuple(int(Fraction(w)*den) for w in weights)


def initial_form(f, weights):
    """The terms of ``f`` of maximal weight for the weight vector."""
    ring = f.ring
    best, terms = None, []
    for monom, coeff in f.terms():
        w = sum(a*b for a, b in zip(weights, monom))
        if best is None or w > best:
            best, terms = w, [(monom, coeff)]
        elif w == best:
            terms.append((monom, coeff))
    return ring.from_dict(dict(terms))


def _spoly_cofactors(f, g, cf, cg, ring):
    """The S-polynomial of ``f`` and ``g`` with its representation."""
    L = monomial_lcm(f.LM, g.LM)
    mf = ring.term_new(monomial_div(L, f.LM), ring.domain.one/f.LC)
    mg = ring.term_new(monomial_div(L, g.LM), ring.domain.one/g.LC)
    s = mf*f - mg*g
    cof = [mf*a - mg*b for a, b in zip(cf, cg)]
    return s, cof


def extended_groebner(F, ring):
    """A Gröbner basis of the ideal generated by ``F`` with the
    representations of its elements in terms of ``F``.

    Returns ``(H, C)`` where ``H`` is a list of polynomials forming a
    Gröbner basis for the order of ``ring`` and ``C[i]`` is a list of
    polynomials with ``H[i] == sum(C[i][j]*F[j] for j)``. This is the
    Buchberger algorithm without any of the optimizations of
    :func:`sympy.polys.groebnertools.groebner`, meant for small inputs such
    as the initial forms of the Gröbner walk.

    Examples
    ========

    >>> from sympy import ring, QQ
    >>> from sympy_extras.polys.groebnerwalk import extended_groebner
    >>> R, x, y = ring("x,y", QQ)
    >>> H, C = extended_groebner([x**2 - y, x*y - 1], R)
    >>> all(h == sum(c*f for c, f in zip(cs, [x**2 - y, x*y - 1])) for h, cs in zip(H, C))
    True
    """
    F = [ring(f) for f in F]
    n = len(F)
    H, C = [], []
    for i, f in enumerate(F):
        if f:
            H.append(f)
            C.append([ring.one if j == i else ring.zero for j in range(n)])
    pairs = [(i, j) for i in range(len(H)) for j in range(i)]
    while pairs:
        i, j = pairs.pop()
        if monomial_lcm(H[i].LM, H[j].LM) == tuple(a + b for a, b in zip(H[i].LM, H[j].LM)):
            continue  # product criterion
        s, cof = _spoly_cofactors(H[i], H[j], C[i], C[j], ring)
        if not s:
            continue
        q, r = s.div(H)
        if not r:
            continue
        for ql, cl in zip(q, C):
            if ql:
                cof = [a - ql*b for a, b in zip(cof, cl)]
        H.append(r)
        C.append(cof)
        pairs.extend((len(H) - 1, l) for l in range(len(H) - 1))
    return H, C


def _convert(G, ring):
    return [ring.from_dict(dict(g)) for g in G]


def _next_weight(G, weights, target):
    """The point of the segment from ``weights`` to ``target`` where the
    ordering of the monomials of ``G`` first changes (``target`` if it
    never does)."""
    tmin = Fraction(1)
    for g in G:
        lm = g.LM
        for m in g.monoms():
            if m == lm:
                continue
            v = [a - b for a, b in zip(lm, m)]
            wv = sum(a*b for a, b in zip(weights, v))
            tv = sum(a*b for a, b in zip(target, v))
            if tv < 0 < wv:
                t = wv/(wv - tv)
                if t < tmin:
                    tmin = t
    return tuple(w + tmin*(t - w) for w, t in zip(weights, target))


def groebner_walk(G, ring, target, check=False, lift='normal_form'):
    """Convert the reduced Gröbner basis ``G`` of ``ring`` (elements of the
    ring, whose order is the source order) to the reduced Gröbner basis for
    the ``target`` order, returned in the ring with that order.

    ``lift`` is ``'normal_form'`` (lifting by normal forms modulo the
    previous basis, the initial forms handled by SymPy's Buchberger
    algorithm) or ``'cofactors'`` (lifting through the representations
    computed by :func:`extended_groebner`).

    Examples
    ========

    >>> from sympy import ring, QQ, grevlex, lex
    >>> from sympy.polys.groebnertools import groebner
    >>> from sympy_extras.polys.groebnerwalk import groebner_walk
    >>> R, x, y, z = ring("x,y,z", QQ, grevlex)
    >>> G = groebner([x*z - y**2, x**2 - y*z], R)
    >>> groebner_walk(G, R, lex)
    [x**2 - y*z, x*y**2 - y*z**2, x*z - y**2, y**4 - y*z**3]
    >>> T = R.clone(order=lex)
    >>> groebner_walk(G, R, lex) == groebner([T.from_dict(dict(g)) for g in [x*z - y**2, x**2 - y*z]], T)
    True
    >>> groebner_walk(groebner_walk(G, R, lex), T, grevlex) == G
    True
    """
    target = as_order(target)
    n = ring.ngens
    G = [ring.from_dict(dict(g)) for g in G]
    if not G or all(not g for g in G):
        return _convert(G, ring.clone(order=target))
    if lift not in ('normal_form', 'cofactors'):
        raise ValueError("lift must be 'normal_form' or 'cofactors'")
    weights = _weight_of(ring.order, n, G)
    tau = _target_weight(target, n)
    current = ring
    while True:
        new_order = WeightOrder(_integral(weights), target)
        new_ring = ring.clone(order=new_order)
        initial = [_convert([initial_form(g, weights)], new_ring)[0] for g in G]
        if lift == 'cofactors':
            H, C = extended_groebner(initial, new_ring)
            G_new = _convert(G, new_ring)
            lifted = []
            for cof in C:
                h = new_ring.zero
                for c, g in zip(cof, G_new):
                    if c:
                        h += c*g
                lifted.append(h)
        else:
            H = _groebner(initial, new_ring)
            lifted = []
            for h in H:
                h_old = _convert([h], current)[0]
                lifted.append(_convert([h_old - h_old.rem(G)], new_ring)[0])
        G = red_groebner(lifted, new_ring)
        current = new_ring
        if check and not is_groebner(G, new_ring):
            raise RuntimeError("the lifted basis is not a Groebner basis")
        if weights == tau:
            break
        weights = _next_weight(G, weights, tau)
    R = ring.clone(order=target)
    G = red_groebner(_convert(G, R), R)
    return sorted(G, key=lambda g: R.order(g.LM), reverse=True)
