r"""Radicals, prime components and primary decompositions of polynomial
ideals of any dimension.

The zeros of an ideal `I` of `\mathbb{Q}[x_1, \ldots, x_n]` are, by a
triangular decomposition in the sense of Kalkbrener
(:func:`~sympy_extras.polys.regularchains.triangularize`), the union of the
closures of the quasi-components of regular chains `T_1, \ldots, T_r`. The
chains are squarefree, so that their saturated ideals are radical
[Hubert]_, and

.. math::

    \sqrt{I} = \bigcap_i \operatorname{sat}(T_i), \qquad
    \operatorname{sat}(T) = (T) : h_T^\infty,

each of them unmixed, of dimension the number of free variables `u` of the
chain, which are algebraically independent modulo each of its associated
primes. This gives the radical, and its equidimensional parts after the
components of a part which lie in a part of greater dimension are removed
(a saturation).

The prime components of `\operatorname{sat}(T)` are those of its extension
to `\mathbb{Q}(u)[x]`, a radical ideal of dimension zero: for a linear form
`\ell` in the main variables which takes different values at its zeros (*a
separating form*; one of the forms with small integer coefficients of
:func:`~sympy_extras.polys.ideals.separating_forms` is), the ideal of the
polynomials in `u` and `y = \ell` is principal, generated by the minimal polynomial `m(u, y)` of
the form, of degree the degree of the chain; to its irreducible factors
`m_1, \ldots, m_s` answer the primes

.. math::

    P_j = \operatorname{sat}(T) : \Bigl(\prod_{k \ne j} m_k(u, \ell)\Bigr)^\infty .

Everything is done with Gröbner bases over the rationals (eliminations and
saturations by one polynomial): none is computed over `\mathbb{Q}(u)`.

The primary decomposition (:func:`primary_decomposition`) follows Gianni,
Trager and Zacharias [GTZ]_ for the reduction to dimension zero over the
field of rational functions in a maximal independent set of variables,
and splits the contraction of that extension with separators between its
minimal primes, as Shimoyama and Yokoyama do [SY]_; in dimension zero, the
components come from the factors of the minimal polynomial of a separating
form, by linear algebra in the quotient algebra.

References
==========

.. [Hubert] E. Hubert, *Notes on triangular sets and
   triangulation-decomposition algorithms I: polynomial systems*, LNCS 2630
   (2003), for the saturated ideal of a squarefree regular chain.
.. [BeckerWeispfenning] T. Becker, V. Weispfenning, *Gröbner bases*,
   Springer (1993), chapter 8 (separating forms, primality in dimension
   zero, extension and contraction).
"""
from __future__ import annotations

from itertools import combinations
from typing import Optional

from sympy.core.add import Add
from sympy.core.expr import Expr
from sympy.core.mul import Mul
from sympy.core.singleton import S
from sympy.core.symbol import Dummy, Symbol
from sympy.polys.domains import QQ
from sympy.polys.polytools import Poly, factor_list
from sympy.polys.rings import ring

from sympy_extras._typing import as_expr

from .ideals import Ideal, separating_forms
from .modulargroebner import groebner
from .orderings import elimination_order
from .regularchains import RegularChain, triangularize

__all__ = ['radical', 'equidimensional_parts', 'minimal_primes', 'primary_decomposition',
           'associated_primes', 'is_primary', 'independent_set', 'PrimaryComponent']


def _whole_ring(ideal: Ideal) -> Ideal:
    return Ideal([S.One], *ideal.symbols, domain=ideal.domain, order=ideal.order)


def _components(ideal: Ideal) -> list[tuple[RegularChain, Ideal]]:
    """Squarefree regular chains whose saturated ideals intersect in the
    radical of the ideal, without those which contain another one."""
    if ideal.domain != QQ:
        raise NotImplementedError("ideals of positive dimension are decomposed over the rationals only")
    found: list[tuple[RegularChain, Ideal]] = []
    for chain in triangularize(ideal.exprs, *ideal.symbols, mode='kalkbrener'):
        saturated = chain.saturated_ideal()
        found.append((chain, Ideal(saturated.exprs, *ideal.symbols, domain=ideal.domain, order=ideal.order).reduced()))
    kept: list[tuple[RegularChain, Ideal]] = []
    for i, (chain, saturated) in enumerate(found):
        redundant = False
        for j, (_, other) in enumerate(found):
            if i != j and other.subset(saturated) and (j < i or not saturated.subset(other)):
                redundant = True
                break
        if not redundant:
            kept.append((chain, saturated))
    return kept


def _require_rationals(ideal: Ideal) -> None:
    if ideal.domain != QQ:
        raise NotImplementedError("ideals are decomposed over the rationals only")


def _intersection(ideals: list[Ideal], within: Ideal) -> Ideal:
    result = _whole_ring(within)
    first = True
    for ideal in ideals:
        result = ideal if first else result.intersect(ideal)
        first = False
    return result.reduced()


def _without(ideal: Ideal, other: Ideal) -> Ideal:
    """``ideal : other**oo``, for a radical ``ideal`` the intersection of
    its primes which do not contain ``other``: that of the saturations by
    the generators of ``other``."""
    parts = [ideal.saturate(g) for g in other.exprs if not ideal.contains(g)]
    return _intersection([part for part in parts if not part.is_whole_ring()], ideal) if parts else _whole_ring(ideal)


def radical(ideal: Ideal) -> Ideal:
    """The radical of an ideal of a polynomial ring over the rationals.

    Examples
    ========

    >>> from sympy.abc import x, y, z
    >>> from sympy_extras.polys.ideals import Ideal
    >>> from sympy_extras.polys.idealdecomposition import radical
    >>> radical(Ideal([x**2*y, x*y**2], x, y))
    Ideal([x*y], x, y)
    >>> radical(Ideal([(x**2 + y**2 - z**2)**2, (x - y)**3*(x**2 + y**2 - z**2)], x, y, z))
    Ideal([x**2 + y**2 - z**2], x, y, z)
    """
    if not ideal.gens:
        return ideal
    # (no Gröbner basis of the ideal itself is needed: without zeros there
    # is no chain, and the empty intersection is the whole ring)
    return _intersection([saturated for _, saturated in _components(ideal)], ideal)


def equidimensional_parts(ideal: Ideal) -> list[Ideal]:
    """The equidimensional parts of the radical of the ideal, by decreasing
    dimension: the part of dimension `d` is the intersection of the
    minimal primes of the ideal of dimension `d`, and the radical is the
    intersection of the parts.

    Examples
    ========

    A plane, a line and a point:

    >>> from sympy.abc import x, y, z
    >>> from sympy_extras.polys.ideals import Ideal
    >>> from sympy_extras.polys.idealdecomposition import equidimensional_parts
    >>> equidimensional_parts(Ideal([x*z*(z - 1), x*y*(z - 1), x*(x - 1)*(z - 1)], x, y, z))
    [Ideal([x*z - x], x, y, z), Ideal([x - 1, y, z], x, y, z)]
    >>> equidimensional_parts(Ideal([x*z, x*y, x*(x - 1)*(z - 1)], x, y, z))
    [Ideal([x], x, y, z), Ideal([x - 1, y, z], x, y, z)]
    """
    if not ideal.gens:
        return [ideal]
    by_dimension: dict[int, list[Ideal]] = {}
    for chain, saturated in _components(ideal):
        by_dimension.setdefault(chain.dimension, []).append(saturated)
    parts: list[Ideal] = []
    for dimension in sorted(by_dimension, reverse=True):
        part = _intersection(by_dimension[dimension], ideal)
        for greater in parts:
            part = _without(part, greater)
        if not part.is_whole_ring():
            parts.append(part)
    return parts


def _separated(chain: RegularChain, saturated: Ideal) -> tuple[Expr, Expr, Symbol]:
    """A separating linear form in the main variables of the chain, and
    its minimal polynomial over the free ones, in a new variable."""
    main, free, degree = chain.main_variables, chain.free_variables, chain.degree
    y = Dummy('y')
    for form in separating_forms(main, degree):
        eliminant = Ideal(saturated.exprs + [y - form], *main, y, *free).eliminate(main).groebner_basis()
        if len(eliminant) != 1:
            raise RuntimeError("the eliminant of an unmixed ideal is not principal")
        minimal = as_expr(eliminant[0].as_expr())
        if Poly(minimal, y).degree() == degree:
            return form, minimal, y
    raise RuntimeError("no separating linear form was found")


def _primes(chain: RegularChain, saturated: Ideal) -> list[Ideal]:
    """The prime components of the saturated ideal of a squarefree chain."""
    if chain.degree == 1:
        return [saturated]
    form, minimal, y = _separated(chain, saturated)
    factors = [as_expr(f).xreplace({y: form}) for f, _ in factor_list(minimal)[1] if as_expr(f).has(y)]
    if len(factors) == 1:
        return [saturated]
    primes: list[Ideal] = []
    for j in range(len(factors)):
        others = as_expr(Mul(*[f for k, f in enumerate(factors) if k != j]))
        primes.append(saturated.saturate(others).reduced())
    return primes


def minimal_primes(ideal: Ideal) -> list[Ideal]:
    """The minimal primes of the ideal, by decreasing dimension: the ideals
    of the irreducible components (over the rationals) of its zeros.

    Examples
    ========

    >>> from sympy.abc import x, y, z
    >>> from sympy_extras.polys.ideals import Ideal
    >>> from sympy_extras.polys.idealdecomposition import minimal_primes
    >>> minimal_primes(Ideal([x*z - y**2, x**2 - y*z], x, y, z))
    [Ideal([x - z, y - z], x, y, z), Ideal([x, y], x, y, z), Ideal([y**2 + y*z + z**2, x + y + z], x, y, z)]
    >>> minimal_primes(Ideal([x**2 - 2*y**2], x, y))
    [Ideal([x**2 - 2*y**2], x, y)]
    """
    if not ideal.gens:
        return [ideal]
    candidates: list[Ideal] = []
    for chain, saturated in _components(ideal):
        for prime in _primes(chain, saturated):
            if not any(prime == other for other in candidates):
                candidates.append(prime)
    minimal = [p for p in candidates if not any(q is not p and q.subset(p) for q in candidates)]
    return sorted(minimal, key=lambda p: (-p.dimension(), str(p)))


# ----------------------------------------------------------------------
# primary decomposition

PrimaryComponent = tuple[Ideal, Ideal]
"""A primary ideal and its associated prime."""


def independent_set(ideal: Ideal) -> list[Symbol]:
    r"""A maximal independent set of variables modulo a proper ideal: a set
    `u` of variables, as many as the dimension, with `I \cap K[u] = 0`.

    No leading monomial of a Gröbner basis lies in `K[u]`
    [KredelWeispfenning]_; the first such subset of the variables, in the
    order of the combinations, is returned.

    Examples
    ========

    >>> from sympy.abc import x, y, z
    >>> from sympy_extras.polys.ideals import Ideal
    >>> from sympy_extras.polys.idealdecomposition import independent_set
    >>> independent_set(Ideal([x*y, x*z], x, y, z))
    [y, z]
    >>> independent_set(Ideal([x**2 - y, z], x, y, z))
    [y]
    """
    if ideal.is_whole_ring():
        raise ValueError("the whole ring has no independent set")
    leading = ideal.leading_monomials('grevlex')
    n = len(ideal.symbols)
    for subset in combinations(range(n), ideal.dimension()):
        chosen = set(subset)
        if all(any(e and i not in chosen for i, e in enumerate(m)) for m in leading):
            return [ideal.symbols[i] for i in subset]
    raise RuntimeError("no independent set of the size of the dimension")


def _contraction(ideal: Ideal, free: list[Symbol]) -> tuple[Ideal, Expr]:
    r"""The contraction `I K(u)[x] \cap K[x]` of the extension of the ideal
    to the field of rational functions in the independent variables `u`,
    and the polynomial `h` of `K[u]` with contraction `I : h^\infty`.

    The reduced Gröbner basis of `I` for a block order with `x > u` is a
    Gröbner basis of the extension, and the contraction is the saturation
    by the product of the leading coefficients of its elements as
    polynomials in `x` ([GTZ]_, [BeckerWeispfenning]_ chapter 8): here by
    the squarefree part of their least common multiple."""
    main = [s for s in ideal.symbols if s not in free]
    if not free or not main:
        return ideal, S.One
    ordered = main + free
    R = ring(ordered, ideal.domain, elimination_order(len(main), len(ordered)))[0]
    basis = groebner([R.from_expr(g) for g in ideal.exprs], R)
    k = len(main)
    h = Poly(1, *free, domain=ideal.domain)
    for g in basis:
        top = g.LM[:k]
        terms = [c*Mul(*[v**e for v, e in zip(free, m[k:])]) for m, c in g.terms() if m[:k] == top]
        h = h.lcm(Poly(Add(*terms), *free, domain=ideal.domain))
    h = h.sqf_part()
    if h.is_ground:
        return ideal, S.One
    factor = as_expr(h.as_expr())
    return ideal.saturate(factor).reduced(), factor


def _separator(prime: Ideal, others: list[Ideal]) -> Expr:
    """A polynomial in every one of the ``others`` and not in ``prime``
    (none of which contains ``prime``): the product of a generator of each
    which is not in ``prime``, the one of least degree."""
    result: Expr = S.One
    for other in others:
        outside = [g for g in other.groebner_basis() if not prime.contains(g)]
        if not outside:
            raise RuntimeError("a prime contains another one of the same dimension")
        chosen = min(outside, key=lambda g: (g.total_degree(), len(g.terms())))
        result = as_expr(result*chosen.as_expr())
    return result


def _zero_dimensional_components(ideal: Ideal) -> list[PrimaryComponent]:
    r"""The primary components of an ideal of dimension zero [GTZ]_: for a
    linear form `\ell` which takes different values at the zeros, with
    minimal polynomial `\prod_j p_j^{k_j}` modulo the ideal, they are
    `I + (p_j(\ell)^{k_j})`, of primes `\sqrt{I} + (p_j(\ell))` (by the
    Chinese remainder theorem, `p_j(\ell)` is nilpotent modulo the
    component of the zeros of `p_j` and a unit modulo the others). All
    by linear algebra in `K[x]/I`, where saturations by separators need
    eliminations (minutes for four points with coefficients of ten
    digits)."""
    radical = ideal.radical()
    points = radical.vector_space_dimension()
    y = Dummy('y')
    for form in separating_forms(ideal.symbols, points):
        minimal = ideal.minimal_polynomial(form, y)
        if minimal.sqf_part().degree() < points:
            continue
        components: list[PrimaryComponent] = []
        for factor, k in minimal.factor_list()[1]:
            value = as_expr(factor.as_expr().xreplace({y: form}))
            power = Ideal([value**k], *ideal.symbols, domain=ideal.domain, order=ideal.order)
            prime = Ideal([value], *ideal.symbols, domain=ideal.domain, order=ideal.order)
            components.append(((ideal + power).reduced(), (radical + prime).reduced()))
        return components
    raise RuntimeError("no separating linear form was found")


def _top_components(ideal: Ideal) -> tuple[list[PrimaryComponent], Ideal, Expr]:
    """The primary components of ``ideal`` of greatest dimension whose
    primes do not meet `K[u]`, for the independent set `u` of
    :func:`independent_set`, their intersection (the contraction) and the
    polynomial `h` with contraction `I : h^\\infty`."""
    free = independent_set(ideal)
    if not free:
        return _zero_dimensional_components(ideal), ideal, S.One
    contracted, h = _contraction(ideal, free)
    # the extension has dimension zero: every associated prime of the
    # contraction is minimal, of the dimension of the ideal
    primes = minimal_primes(contracted)
    if not primes or any(p.dimension() != len(free) for p in primes):
        raise RuntimeError("the contraction of the extension is not unmixed")
    if len(primes) == 1:
        return [(contracted, primes[0])], contracted, h
    components: list[PrimaryComponent] = []
    for i, prime in enumerate(primes):
        separator = _separator(prime, primes[:i] + primes[i + 1:])
        components.append((contracted.saturate(separator).reduced(), prime))
    return components, contracted, h


def _saturation_exponent(ideal: Ideal, saturated: Ideal, h: Expr) -> int:
    """The least `m` with `I : h^m = I : h^\\infty` (``saturated``): the
    least `m` with `h^m g` in `I` for every generator `g` of the
    saturation, found by normal forms modulo `I` (`I : h^m` is contained
    in the saturation, and contains it once the generators are in it).
    Iterated ideal quotients cost an elimination each, one of a minute on
    an intersection of three random curves."""
    m = 0
    for g in saturated.exprs:
        product = ideal.reduce(g*h**m)
        while product != 0:
            m += 1
            product = ideal.reduce(product*h)
    return m


def _intersection_within(components: list[PrimaryComponent], ideal: Ideal) -> bool:
    """Whether the intersection of the primary ideals is contained in
    ``ideal``."""
    return _intersection([q for q, _ in components], ideal).subset(ideal)


def primary_decomposition(ideal: Ideal) -> list[PrimaryComponent]:
    r"""An irredundant primary decomposition of an ideal of a polynomial
    ring over the rationals, as pairs ``(Q, P)`` of a primary ideal and its
    associated prime, by decreasing dimension of the primes: the ideal is
    the intersection of the ``Q``, and the ``P`` are its associated primes,
    all different, the minimal and the embedded ones.

    The reduction of Gianni, Trager and Zacharias [GTZ]_: for a maximal
    independent set `u` of variables, the extension of `I` to `K(u)[x]`
    has dimension zero, and its contraction `I^c = I : h^\infty`, for the
    product `h \in K[u]` of the leading coefficients of a Gröbner basis for
    a block order, is the intersection of the primary components of `I`
    whose primes do not meet `K[u]`; they are the minimal primes of `I^c`,
    which has no embedded ones. With `m` such that `I : h^m = I^c`,

    .. math::

        I = I^c \cap (I + (h^m)),

    and the recursion goes on with `I + (h^m)`, a larger ideal. The
    components of `I^c` are split, instead of by a primary decomposition
    over `K(u)` (a separating linear form and the factors of its minimal
    polynomial), by separators, as Shimoyama and Yokoyama do [SY]_: the
    minimal primes `P_1, \ldots, P_r` of `I^c` are known
    (:func:`minimal_primes`), and for `s_i` in the other primes and not in
    `P_i`, `I^c : s_i^\infty` is the `P_i`-primary component. The
    components found are finally merged by prime, and those which contain
    the intersection of the others are removed.

    Examples
    ========

    The ``y`` axis with an embedded point at the origin:

    >>> from sympy.abc import x, y, z
    >>> from sympy_extras.polys.ideals import Ideal
    >>> from sympy_extras.polys.idealdecomposition import primary_decomposition
    >>> primary_decomposition(Ideal([x**2, x*y], x, y))
    [(Ideal([x], x, y), Ideal([x], x, y)), (Ideal([x**2, y], x, y), Ideal([x, y], x, y))]

    Three lines, one of them doubled:

    >>> for Q, P in primary_decomposition(Ideal([x*z, y**2*z, (x - 1)**2*y], x, y, z)):
    ...     print(Q, P)
    Ideal([x**2 - 2*x + 1, z], x, y, z) Ideal([x - 1, z], x, y, z)
    Ideal([x, y], x, y, z) Ideal([x, y], x, y, z)
    Ideal([y, z], x, y, z) Ideal([y, z], x, y, z)

    References
    ==========

    .. [GTZ] P. Gianni, B. Trager, G. Zacharias, *Gröbner bases and
       primary decomposition of polynomial ideals*, J. Symbolic Comput. 6
       (1988) 149-167.
    .. [SY] T. Shimoyama, K. Yokoyama, *Localization and primary
       decomposition of polynomial ideals*, J. Symbolic Comput. 22 (1996)
       247-277.
    .. [KredelWeispfenning] H. Kredel, V. Weispfenning, *Computing
       dimension and independent sets for polynomial ideals*, J. Symbolic
       Comput. 6 (1988) 231-247.
    """
    _require_rationals(ideal)
    if ideal.is_whole_ring():
        return []
    if not ideal.gens:
        return [(ideal, ideal)]
    found: list[PrimaryComponent] = []
    current = ideal.reduced()
    # the intersection of the components found, to stop as soon as it is
    # the ideal: the steps after that one find redundant components only
    # (and a step can take minutes)
    found_so_far: Optional[Ideal] = None
    while not current.is_whole_ring():
        components, contracted, h = _top_components(current)
        found.extend(components)
        if contracted == current:
            break
        found_so_far = contracted if found_so_far is None else found_so_far.intersect(contracted).reduced()
        if all(ideal.contains(g) for g in found_so_far.gens):
            break
        m = _saturation_exponent(current, contracted, h)
        power = Ideal([h**m], *ideal.symbols, domain=ideal.domain, order=ideal.order)
        current = (current + power).reduced()
    # the primes of different steps differ (those of a step contain the h
    # of the steps before it, which lies outside the primes of that step);
    # merge anyway, then drop the components which contain the
    # intersection of the others, the embedded ones (found last) first
    merged: list[PrimaryComponent] = []
    for q, p in found:
        for i, (q2, p2) in enumerate(merged):
            if p == p2:
                merged[i] = (q2.intersect(q).reduced(), p2)
                break
        else:
            merged.append((q, p))
    kept = list(merged)
    for component in reversed(merged):
        others = [c for c in kept if c is not component]
        if others and _intersection_within(others, component[0]):
            kept = others
    return sorted(kept, key=lambda c: (-c[1].dimension(), str(c[1])))


def associated_primes(ideal: Ideal) -> list[Ideal]:
    """The associated primes of the ideal, minimal and embedded, by
    decreasing dimension: the primes of its primary decomposition.

    Examples
    ========

    >>> from sympy.abc import x, y, z
    >>> from sympy_extras.polys.ideals import Ideal
    >>> from sympy_extras.polys.idealdecomposition import associated_primes
    >>> associated_primes(Ideal([x**2, x*y], x, y))
    [Ideal([x], x, y), Ideal([x, y], x, y)]
    >>> associated_primes(Ideal([x*y, x*z, y*z], x, y, z))
    [Ideal([x, y], x, y, z), Ideal([x, z], x, y, z), Ideal([y, z], x, y, z)]
    """
    return [p for _, p in primary_decomposition(ideal)]


def is_primary(ideal: Ideal) -> bool:
    r"""Whether the ideal is primary: it has one minimal prime `P` and
    equals its contraction from `K(u)[x]` for a maximal independent set
    `u` (a primary ideal is the contraction of its extension to a
    localization at a multiplicative set outside `P`; conversely the
    contraction is the intersection of the primary components whose primes
    do not meet `K[u]`, all of them minimal).

    Examples
    ========

    >>> from sympy.abc import x, y, z
    >>> from sympy_extras.polys.ideals import Ideal
    >>> from sympy_extras.polys.idealdecomposition import is_primary
    >>> is_primary(Ideal([x**2, y**3], x, y)), is_primary(Ideal([x**2, x*y], x, y))
    (True, False)
    >>> is_primary(Ideal([x**2, y], x, y, z)), is_primary(Ideal([x*y], x, y))
    (True, False)
    """
    _require_rationals(ideal)
    if ideal.is_whole_ring():
        return False
    if not ideal.gens:
        return True
    contracted, _ = _contraction(ideal, independent_set(ideal))
    return contracted == ideal and len(minimal_primes(ideal)) == 1
