r"""Radicals and prime components of polynomial ideals of any dimension.

The zeros of an ideal `I` of `\mathbb{Q}[x_1, \ldots, x_n]` are, by a
triangular decomposition in the sense of Kalkbrener
(:func:`~sympy_extras.polys.regularchains.triangularize`), the union of the
closures of the quasi-components of regular chains `T_1, \ldots, T_r`. The
chains are squarefree, so that their saturated ideals are radical
[Hubert]_, and

.. math::

    \sqrt{I} = \bigcap_i \operatorname{sat}(T_i), \qquad
    \operatorname{sat}(T) = (T) : h_T^\infty,

each of them unmixed, of dimension the number of free variables `u` of the
chain, which are algebraically independent modulo each of its associated
primes. This gives the radical, and its equidimensional parts after the
components of a part which lie in a part of greater dimension are removed
(a saturation).

The prime components of `\operatorname{sat}(T)` are those of its extension
to `\mathbb{Q}(u)[x]`, a radical ideal of dimension zero: for a linear form
`\ell` in the main variables which takes different values at its zeros (*a
separating form*; one of `x_1 + t x_2 + t^2 x_3 + \cdots`, `t = 0, 1,
\ldots` is [BeckerWeispfenning]_), the ideal of the polynomials in `u` and
`y = \ell` is principal, generated by the minimal polynomial `m(u, y)` of
the form, of degree the degree of the chain; to its irreducible factors
`m_1, \ldots, m_s` answer the primes

.. math::

    P_j = \operatorname{sat}(T) : \Bigl(\prod_{k \ne j} m_k(u, \ell)\Bigr)^\infty .

Everything is done with Gröbner bases over the rationals (eliminations and
saturations by one polynomial): none is computed over `\mathbb{Q}(u)`.

References
==========

.. [Hubert] E. Hubert, *Notes on triangular sets and
   triangulation-decomposition algorithms I: polynomial systems*, LNCS 2630
   (2003), for the saturated ideal of a squarefree regular chain.
.. [BeckerWeispfenning] T. Becker, V. Weispfenning, *Gröbner bases*,
   Springer (1993), chapter 8 (separating forms, primality in dimension
   zero, extension and contraction).
"""
from __future__ import annotations

from sympy.core.expr import Expr
from sympy.core.mul import Mul
from sympy.core.singleton import S
from sympy.core.symbol import Dummy, Symbol
from sympy.polys.domains import QQ
from sympy.polys.polytools import Poly, factor_list

from sympy_extras._typing import as_expr

from .ideals import Ideal
from .regularchains import RegularChain, triangularize

__all__ = ['radical', 'equidimensional_parts', 'minimal_primes']


def _whole_ring(ideal: Ideal) -> Ideal:
    return Ideal([S.One], *ideal.symbols, domain=ideal.domain, order=ideal.order)


def _components(ideal: Ideal) -> list[tuple[RegularChain, Ideal]]:
    """Squarefree regular chains whose saturated ideals intersect in the
    radical of the ideal, without those which contain another one."""
    if ideal.domain != QQ:
        raise NotImplementedError("ideals of positive dimension are decomposed over the rationals only")
    found: list[tuple[RegularChain, Ideal]] = []
    for chain in triangularize(ideal.exprs, *ideal.symbols, mode='kalkbrener'):
        saturated = chain.saturated_ideal()
        found.append((chain, Ideal(saturated.exprs, *ideal.symbols, domain=ideal.domain, order=ideal.order).reduced()))
    kept: list[tuple[RegularChain, Ideal]] = []
    for i, (chain, saturated) in enumerate(found):
        redundant = False
        for j, (_, other) in enumerate(found):
            if i != j and other.subset(saturated) and (j < i or not saturated.subset(other)):
                redundant = True
                break
        if not redundant:
            kept.append((chain, saturated))
    return kept


def _intersection(ideals: list[Ideal], within: Ideal) -> Ideal:
    result = _whole_ring(within)
    first = True
    for ideal in ideals:
        result = ideal if first else result.intersect(ideal)
        first = False
    return result.reduced()


def _without(ideal: Ideal, other: Ideal) -> Ideal:
    """``ideal : other**oo``, for a radical ``ideal`` the intersection of
    its primes which do not contain ``other``: that of the saturations by
    the generators of ``other``."""
    parts = [ideal.saturate(g) for g in other.exprs if not ideal.contains(g)]
    return _intersection([part for part in parts if not part.is_whole_ring()], ideal) if parts else _whole_ring(ideal)


def radical(ideal: Ideal) -> Ideal:
    """The radical of an ideal of a polynomial ring over the rationals.

    Examples
    ========

    >>> from sympy.abc import x, y, z
    >>> from sympy_extras.polys.ideals import Ideal
    >>> from sympy_extras.polys.idealdecomposition import radical
    >>> radical(Ideal([x**2*y, x*y**2], x, y))
    Ideal([x*y], x, y)
    >>> radical(Ideal([(x**2 + y**2 - z**2)**2, (x - y)**3*(x**2 + y**2 - z**2)], x, y, z))
    Ideal([x**2 + y**2 - z**2], x, y, z)
    """
    if not ideal.gens:
        return ideal
    # (no Gröbner basis of the ideal itself is needed: without zeros there
    # is no chain, and the empty intersection is the whole ring)
    return _intersection([saturated for _, saturated in _components(ideal)], ideal)


def equidimensional_parts(ideal: Ideal) -> list[Ideal]:
    """The equidimensional parts of the radical of the ideal, by decreasing
    dimension: the part of dimension `d` is the intersection of the
    minimal primes of the ideal of dimension `d`, and the radical is the
    intersection of the parts.

    Examples
    ========

    A plane, a line and a point:

    >>> from sympy.abc import x, y, z
    >>> from sympy_extras.polys.ideals import Ideal
    >>> from sympy_extras.polys.idealdecomposition import equidimensional_parts
    >>> equidimensional_parts(Ideal([x*z*(z - 1), x*y*(z - 1), x*(x - 1)*(z - 1)], x, y, z))
    [Ideal([x*z - x], x, y, z), Ideal([x - 1, y, z], x, y, z)]
    >>> equidimensional_parts(Ideal([x*z, x*y, x*(x - 1)*(z - 1)], x, y, z))
    [Ideal([x], x, y, z), Ideal([x - 1, y, z], x, y, z)]
    """
    if not ideal.gens:
        return [ideal]
    by_dimension: dict[int, list[Ideal]] = {}
    for chain, saturated in _components(ideal):
        by_dimension.setdefault(chain.dimension, []).append(saturated)
    parts: list[Ideal] = []
    for dimension in sorted(by_dimension, reverse=True):
        part = _intersection(by_dimension[dimension], ideal)
        for greater in parts:
            part = _without(part, greater)
        if not part.is_whole_ring():
            parts.append(part)
    return parts


def _separated(chain: RegularChain, saturated: Ideal) -> tuple[Expr, Expr, Symbol]:
    """A separating linear form in the main variables of the chain, and
    its minimal polynomial over the free ones, in a new variable."""
    main, free, degree = chain.main_variables, chain.free_variables, chain.degree
    y = Dummy('y')
    # the forms which do not separate two of the `degree` zeros lie on a
    # hyperplane for each pair, and a hyperplane has at most len(main) - 1
    # of the points (1, t, t**2, ...)
    for t in range((len(main) - 1) * degree * (degree - 1) // 2 + 1):
        form = as_expr(sum((Mul(t**i, v) for i, v in enumerate(main)), S.Zero))
        eliminant = Ideal(saturated.exprs + [y - form], *main, y, *free).eliminate(main).groebner_basis()
        if len(eliminant) != 1:
            raise RuntimeError("the eliminant of an unmixed ideal is not principal")
        minimal = as_expr(eliminant[0].as_expr())
        if Poly(minimal, y).degree() == degree:
            return form, minimal, y
    raise RuntimeError("no separating linear form was found")


def _primes(chain: RegularChain, saturated: Ideal) -> list[Ideal]:
    """The prime components of the saturated ideal of a squarefree chain."""
    if chain.degree == 1:
        return [saturated]
    form, minimal, y = _separated(chain, saturated)
    factors = [as_expr(f).xreplace({y: form}) for f, _ in factor_list(minimal)[1] if as_expr(f).has(y)]
    if len(factors) == 1:
        return [saturated]
    primes: list[Ideal] = []
    for j in range(len(factors)):
        others = as_expr(Mul(*[f for k, f in enumerate(factors) if k != j]))
        primes.append(saturated.saturate(others).reduced())
    return primes


def minimal_primes(ideal: Ideal) -> list[Ideal]:
    """The minimal primes of the ideal, by decreasing dimension: the ideals
    of the irreducible components (over the rationals) of its zeros.

    Examples
    ========

    >>> from sympy.abc import x, y, z
    >>> from sympy_extras.polys.ideals import Ideal
    >>> from sympy_extras.polys.idealdecomposition import minimal_primes
    >>> minimal_primes(Ideal([x*z - y**2, x**2 - y*z], x, y, z))
    [Ideal([x - z, y - z], x, y, z), Ideal([x, y], x, y, z), Ideal([y**2 + y*z + z**2, x + y + z], x, y, z)]
    >>> minimal_primes(Ideal([x**2 - 2*y**2], x, y))
    [Ideal([x**2 - 2*y**2], x, y)]
    """
    if not ideal.gens:
        return [ideal]
    candidates: list[Ideal] = []
    for chain, saturated in _components(ideal):
        for prime in _primes(chain, saturated):
            if not any(prime == other for other in candidates):
                candidates.append(prime)
    minimal = [p for p in candidates if not any(q is not p and q.subset(p) for q in candidates)]
    return sorted(minimal, key=lambda p: (-p.dimension(), str(p)))
